# Generated by Django 4.1.3 on 2022-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0002_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present_status',
            field=models.CharField(blank=True, default='absent', max_length=50, null=True),
        ),
    ]
