# Generated by Django 4.1.3 on 2022-12-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('product_out', models.CharField(blank=True, max_length=80, null=True)),
                ('product_return', models.CharField(blank=True, max_length=80, null=True)),
                ('final_price', models.FloatField(blank=True, max_length=80, null=True)),
                ('damage_product', models.CharField(blank=True, max_length=80, null=True)),
                ('damage_price', models.FloatField(blank=True, max_length=80, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.group')),
            ],
        ),
    ]
