# Generated by Django 4.1.3 on 2022-12-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductName',
            new_name='Products',
        ),
    ]
