# Generated by Django 4.1.3 on 2022-12-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productname_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='damage_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='damage_product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_out',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_return',
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_out', models.CharField(blank=True, max_length=80, null=True)),
                ('product_return', models.CharField(blank=True, max_length=80, null=True)),
                ('final_price', models.FloatField(blank=True, max_length=80, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='DamageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('price', models.FloatField(blank=True, max_length=80, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.group')),
            ],
        ),
    ]
