# Generated by Django 4.1.3 on 2022-12-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_damage_price_products_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstatus',
            old_name='products',
            new_name='product',
        ),
    ]
