# Generated by Django 4.1.3 on 2022-12-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_products_productstatus_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ProductGroup',
        ),
    ]
