# Generated by Django 4.1.3 on 2022-12-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_group_productgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damageproduct',
            old_name='group',
            new_name='product_group',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='group',
            new_name='product_group',
        ),
    ]
